### ISSUE TITLE
How to install with Resharper 2016.2?

### ISSUE THREAD

**Issue by lucasrabiec** [Huntk23/ResharperGlyphfriend#7]
@Huntk23 
How to install your plugin in VS 2015 and ReSharper Ultimate 2016.2? I try this: [solution](https://resharper-support.jetbrains.com/hc/en-us/articles/207241675-Offline-plug-in-installation-process) with version 0.8.1, but it doesn't work. In the ReSharper Gallery in VS i have only 53 extensions (without yours).

Any tips?

**Comment by NLI-KelbyHunt** [comment]
@LukaszRabiec I have updated it for 2016.2. Since 2016.3 is probably a week or two from releasing I'll update it to that version.

**Comment by Huntk23** [comment]
@LukaszRabiec I have not updated it for 2016.2. Since 2016.3 is probably a week or two from releasing I'll update it to that version.

**Comment by lucasrabiec** [comment]
Oh, it's great! I'm waiting, thank you! :)
