### ISSUE TITLE
FontAwesome incorrect file names in project 

### ISSUE THREAD

**Issue by grifin85** [Huntk23/ResharperGlyphfriend#8]
In project you set file name like **fa-caret-square-o-left.png** nut in folder we can see fa-caret-square-o-**left[DarkGray].png** and **fa-caret-square-o-left[Gray].png**

**Comment by Huntk23** [comment]
This is because I am in the process of making this extension Theme friendly. I am closing this for now as it isn't technically a bug but just code in the middle of development.
